### ISSUE TITLE
The move to list doesn't work

### ISSUE THREAD

**Issue by abhixec** [smallhadroncollider/taskell#11]
The move to list though lists other columns when you click on the button corresponding to that list it doesn't move the item to that list.

Example: 
In default markdown you have todo and done. If you go to the taskell.md and add another column "Later" 
Open taskell create a new task and try moving it to the newly created "Later" column it doesn't work.

**Comment by smallhadroncollider** [comment]
It does seem to work *some* of the time: if you try moving it to a column *before* the one you're in. Seems to be if it's *after* the current column that things go wrong.

I added some code a while back so that it wouldn't let you move it to the column you're currently in, but it looks like it broke the code that does the moving.

I'll have a look at this later today and add some unit tests.

**Comment by smallhadroncollider** [comment]
Fixed in [1.2.0](https://github.com/smallhadroncollider/taskell/releases/tag/1.2.0)
