### ISSUE TITLE
taskell: taskell.md: openBinaryFile: resource busy (file is locked)

### ISSUE THREAD

**Issue by jamesworcester** [smallhadroncollider/taskell#18]
When I try to move items up and down a board or left and right between boards two times or more in rapid succession, taskell outputs the following message at random points across the terminal: 
`taskell: taskell.md: openBinaryFile: resource busy (file is locked)`.

I presume this is because I have many items with very lengthy description lists, and taskell is having difficulty rearranging them inside `~/taskell.md` and relocking the file before I try to move them again. I would imagine this could be solved by doing something like having taskell instead write each item and description to invidual files, then just change the order of the symlinks within the master file (currently `~/taskell.md`) whenever a user rearranges an item. Something like that would also probably dramatically save on system load when changing the order of items within taskell, and would be especially noticeable by users with large lists of notes.

I am currently running taskell through the supplied binary file on Gentoo Linux, and my current `~/taskell.md` file is 21.6K big and contains 715 lines of text. Love the program, thanks for developing it.

**Comment by smallhadroncollider** [comment]
Thanks for this. The write code is fairly simplistic at the moment - clearly needs a bit of work.

I'm on parental leave for the next few months, but I'll look into this one ASAP.

**Comment by jamesworcester** [comment]
No worries mate, enjoy being a parent first :stuck_out_tongue:

**Comment by smallhadroncollider** [comment]
So, I've had a few thoughts on this:

1. Change it so that writes only happen on quit rather than whenever a change is detected: this would be simple and make taskell much more efficient, but I'm not sure it's ideal as it would mean needing to quit taskell whenever you wanted to update the file. Personally I keep taskell permanently open in a separate window, so this is not ideal. I suppose it could be configurable and off by default.

2. Use "debouncing": make it so it doesn't try and do more than one write per second (or some other interval). This would be quite easy to implement, but always feels a tad arbitrary.

3. Do some proper profiling and try and address the underlying performance issues. This is definitely the *right* answer, but it's also the most time consuming. However, I can see there are lots of aspects that could be improved:

    - Currently the write process starts and taskell loses all control of it. Would be better if it could be cancelled and started again. Probably shouldn't have stray processes for all sorts of reasons.
    - When it writes the file it recalculates all of the formatting, even if only a tiny part has changed. I could use caching to remove a lot of the overhead. It's crazy inefficient at the moment.
    - I've not done any performance profiling at all - haven't got that far with Haskell yet. So there are probably all sorts of optimisations that could be made elsewhere.

I'm thinking maybe I put in debouncing as a provisional measure and then work towards removing it at a later date.

**Comment by jamesworcester** [comment]
Yeah I was thinking the same thing, a quick debouncing patch job in the interim would be very effective for the end user, then you can take the time you need to learn Haskell and implement some efficiency and performance boons when it works for you.

I do think it's important to do a quick deboucing patch, as I did experience some data loss at times when I was quickly moving large items with lengthy descriptions around the kanban board, and it sounds like debouncing would fix that right up

**Comment by smallhadroncollider** [comment]
Yes, indeed. Going to try and get it in before the end of the week.

**Comment by jamesworcester** [comment]
Alright mate, great job, keep it up!

**Comment by smallhadroncollider** [comment]
Ok, debouncing is in with [1.3.5](https://github.com/smallhadroncollider/taskell/releases/tag/1.3.5). Could you give it a go and let me know if it fixes the issue?

I've tried it on a large file I created and it seems to work. Performance is still sluggish because of the redraw code, but it's writing to disk less often. However, I couldn't get the `resource busy (file is locked)` error before I added debouncing (it was just *very* slow), so can't be sure it fixes it.

**Comment by jamesworcester** [comment]
Well done, on my end that fixes everything with a pretty damn large file, no more `resource busy (file is locked)` errors, no more data loss, it works very well

**Comment by smallhadroncollider** [comment]
Excellent. It occurs to me that if you made a change and then quit almost immediately you'd possibly still get the issue, but that's fairly unlikely.

In any case, I hope that I might be able to remove the debouncing at some point. I'm going to close this issue for now, but I'll try and remember to let you know if I fix the problem in a more rigorous manner.
