### ISSUE TITLE
libtinfo.so.5: no version information available

### ISSUE THREAD

**Issue by lbenezriravin** [smallhadroncollider/taskell#26]
This looks like the same issue as #17 

When downloading the binary, I get that message whenever I run taskell. I built from source, and don't see the same problem. I'm running Fedora 29 and `ncurses-compat-libs` is installed.

Huge thanks for a great tool!

**Comment by smallhadroncollider** [comment]
Have you tried installing `ncurses-compat-libs`?

**Comment by lbenezriravin** [comment]
Yes, I have ncurses-compat-libs installed

**Comment by smallhadroncollider** [comment]
Ah, yes, you did say (sorry, young child, bit sleep deprived).

I only do binaries for Mac and Ubuntu (Debian) as I can't guarantee they'll work on any other platforms. Building from scratch is probably the best course of action.

**Comment by lbenezriravin** [comment]
Sure. If I see the same issue on a debian-based system I'll re-open.

**Comment by smallhadroncollider** [comment]
I will update the Readme so it says Debian instead of Linux.

Basically, Stack (the build tool) can automatically build a version with their Docker image. But they only have an Ubuntu image. The Stack documentation isn't the best, so I've no idea if I could do it with another distro/docker image.

**Comment by Ian2020** [comment]
I know this is closed but thought I'd add what I learnt from a little research, it's a distro specific problem. According to https://stackoverflow.com/a/63730734/28170 this message is caused by Fedora not building ncurses with symbol versioning information (whereas Debian does). A [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1875587) has been raised on Fedora but it's almost couple of years old now and no progress. The fix suggested on stackoverflow is to build ncurses yourself and enable the symbol versioning.
