### ISSUE TITLE
Use XDG Specification

### ISSUE THREAD

**Issue by mstruebing** [smallhadroncollider/taskell#28]
Hey, you should respect the XDG specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html 

I'll try to implement that soonish, but wanted to create an issue for that first.

Good article about that: https://0x46.net/thoughts/2019/02/01/dotfile-madness/

**Comment by smallhadroncollider** [comment]
I read that article the other day and thought "I should do that", then completely forgot about it (I have a six month old, so that's a pretty common occurrence at the moment).

If you do decide to implement it (thanks!), please make sure that it still looks in `~/.taskell` if it can't find it anywhere else, so it doesn't break old installs.
