### ISSUE TITLE
Confirm message(s)?

### ISSUE THREAD

**Issue by matthiasbeyer** [smallhadroncollider/taskell#33]
Would be nice to have a confirmation-question when hitting `q` or `C` or starting any other destructive operation.

**Comment by smallhadroncollider** [comment]
I've always preferred the ["undo over warning"](http://alistapart.com/article/neveruseawarning/) approach. You can use `u` to undo pretty much everything.

The only exception is if you pressed `q` immediately after doing something destructive. I could potentially serialize the undo state and store it on quit so that undo is preserved between sessions. I'm a big fan of this functionality in Vim.

The other alternative would be to make quitting slightly more involved somehow. Although I don't want to make it so that people can't quit all of a sudden, so would need to be optional.

Are there any other cases you can think of where you can do something destructive without being able to undo?

**Comment by matthiasbeyer** [comment]
Hm. I'm mainly concerned about the quit operation. I wouldn't even mind having an option in the config file to set "ask-quit = true" or something like that.

I do not care about do/undo (only if I cannot undo) but mainly about the interruption of my workflow. quit and re-enter the application breaks my workflow if I accidentially hit `q`.

**Comment by smallhadroncollider** [comment]
You could change the bindings to make `quit` harder to hit by accident?

For example on Mac:

```
quit = œ
```

That would be `alt+q`, which you're unlikely to hit by accident. I imagine something similar works in Linux and Windows?

**Comment by matthiasbeyer** [comment]
Hmh. I will try that and report back...

**Comment by smallhadroncollider** [comment]
@matthiasbeyer Success?

**Comment by matthiasbeyer** [comment]
Had no opportunity yet, but will have one this weekend (because hacking event). Stay tuned!

**Comment by matthiasbeyer** [comment]
I tried to create `~/.config/taskell/bindings.ini` with contents `quit = Z` but it didn't work at all, I still need to hit `q` for exiting. hmmh...

**Comment by smallhadroncollider** [comment]
Hmm, have you got the latest version (`>= 1.4.0`)? Should create the `bindings.ini` file for you.

**Comment by matthiasbeyer** [comment]
Ah, I had to update the nixpks, ... works for me now!
